spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 1234
  main:
    allow-bean-definition-overriding: true

jwt:
  accessToken-expiration-date: 86400000